name: "MetaCall Distributable Linux Test"

# CI used for testing the development environment

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Run Tests
        run: |
          make
          if [ ! -f out/tarball.tar.gz ]; then
              echo "Failed to generate the tarball"
              exit 1
          fi

      - name: Clear
        run: |
          make clear
          if [ -f out/tarball.tar.gz ]; then
              echo "Failed clear the tarball"
              exit 1
          fi
